### ISSUE TITLE
无法过wd

### ISSUE THREAD

**Issue by zuesdevil** [H4de5-7/powershell-bypass#2]
师傅，我貌似没过wd，还需要咋设置一下吗？

![1667311553233](https://user-images.githubusercontent.com/42496487/199252616-af522973-05d3-4060-8d2d-626957bd7278.png)

**Comment by H4de5-7** [comment]
Defender这里比较玄学感觉。。有偶然的时候过不了，我测试了很多次，可能有一两次会拦，但是不会查杀exe，可以再运行一下试试。。我觉得应该是特征太明显了，毕竟是明文，这个只是个demo，可能需要自己设置一下自定义的加密方法，我过两天要是有空的话弄一个简单的加密

**Comment by H4de5-7** [comment]
> 师傅，我貌似没过wd，还需要咋设置一下吗？
> 
> ![1667311553233](https://user-images.githubusercontent.com/42496487/199252616-af522973-05d3-4060-8d2d-626957bd7278.png)

可以看一下你的命令吗，这个报错我感觉没见过

**Comment by zuesdevil** [comment]
嗯嗯，好的，感谢师傅。exe是不会被杀的

**Comment by H4de5-7** [comment]
> 嗯嗯，好的，感谢师傅。exe是不会被杀的

其实这个小工具我最开始是用来上线之后免杀执行计划任务这种powershell命令的，但后来发现好像能免杀上线。。但是最近太忙了，只写了一个小demo，后续有空会补下。

**Comment by H4de5-7** [comment]
师傅好，已更新，这一版应该没问题了。

**Comment by H4de5-7** [comment]
莫事hhh
