### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hiyoshiy** [H4de5-7/powershell-bypass#3]
师傅这怎么解决，编译不出来

![image](https://user-images.githubusercontent.com/98879280/203511463-7791a490-36e2-45e3-9efc-c7fb8a6ac08c.png)

**Comment by H4de5-7** [comment]
我的问题不好意思了。。昨天改的时候忘加了一个using，现在已经修改了，师傅可以再试一下。

**Comment by hiyoshiy** [comment]
讲18行空格替换为+之后还是报错了，师傅麻烦看一下
![image](https://user-images.githubusercontent.com/98879280/203523777-fc98d30a-ea6a-4765-a6c6-b272f31a3845.png)

**Comment by H4de5-7** [comment]
是不是少了个引号，在/a后面。

**Comment by hiyoshiy** [comment]
好的感谢老哥

**Comment by H4de5-7** [comment]
莫事。
